### ISSUE TITLE
Crash when re-spawning 

### ISSUE THREAD

**Issue by RangerNorth** [TheChildWalrus/SiegeMode#2]
I was testing the mod in a single player environment all of the commands worked flawlessly except for respawning. Just to see if it would reload my inventory I jumped off the tower that I was testing the siege mode mod with, and when I clicked respawn the game loaded me in and then proceeded to crash in about 3 seconds after respawning. I have the crash report if needed, please help!

**Comment by MilkMC** [comment]
Yes, please post the crash report.

**Comment by RangerNorth** [comment]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 6/16/17 6:40 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at siege.common.siege.Siege.applyPlayerKit(Siege.java:777)
	at siege.common.siege.Siege.onPlayerRespawn(Siege.java:750)
	at siege.common.EventHandler.onPlayerRespawn(EventHandler.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_900_EventHandler_onPlayerRespawn_PlayerRespawnEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerRespawnEvent(FMLCommonHandler.java:560)
	at net.minecraft.server.management.ServerConfigurationManager.func_72368_a(ServerConfigurationManager.java:486)
	at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:860)
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:50)
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at siege.common.siege.Siege.applyPlayerKit(Siege.java:777)
	at siege.common.siege.Siege.onPlayerRespawn(Siege.java:750)
	at siege.common.EventHandler.onPlayerRespawn(EventHandler.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_900_EventHandler_onPlayerRespawn_PlayerRespawnEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerRespawnEvent(FMLCommonHandler.java:560)
	at net.minecraft.server.management.ServerConfigurationManager.func_72368_a(ServerConfigurationManager.java:486)
	at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:860)
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:50)
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1c23564
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 628984104 bytes (599 MB) / 2098085888 bytes (2000 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 111 mods loaded, 111 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{IvToolkit} [1.0.3] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal (1).jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJAAAA	ExtendedPotions{1.2} [Extended Potions] (ExtendedPotions-MC1.7.10-1.2.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3 (2).jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4 (1).jar) 
	UCHIJAAAA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJAAAA	lotr{Beta v32.3 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod B32.3.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
	UCHIJAAAA	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	Aquaculture{1.2.6} [Aquaculture] (Aquaculture-1.7.10-1.2.6.21.jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAA	Artifacts{1.1.3} [Artifacts] (Artifacts-1.1.3.jar) 
	UCHIJAAAA	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
	UCHIJAAAA	betterquesting{2.0.224} [Better Questing] (BetterQuesting-2.0.224.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1826-universal.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16) (1).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	doorsoplenty{0.1} [Doors o Plenty] (doorsoplenty-1.0.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar) 
	UCHIJAAAA	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10 (1).jar) 
	UCHIJAAAA	dragonrealm{1.2a} [Dragon Realm] (DragonRealm_v1.2a.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHIJAAAA	etfuturum{1.5.5} [Et Futurum] (Et Futurum-1.5.5.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCHIJAAAA	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	imc{1.12.3-MC1.7.10} [Improving Minecraft] (Improving Minecraft-1.12.3 for Minecraft 1.7.10.jar) 
	UCHIJAAAA	instantblocks{1.5.4} [Instant Blocks] (InstantBlocks_v1.5.4.jar) 
	UCHIJAAAA	journeymap{5.1.4} [JourneyMap] (journeymap-1.7.10-5.1.4-unlimited.jar) 
	UCHIJAAAA	locks{1.0.0} [Locks] (Locks-1.0.0.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAA	MCP_API{1.4} [MC+ API] (MC-Mod-API-1.7.10.jar) 
	UCHIJAAAA	MCP_Wheel{1.1.2} [MC+ Wheel] (MC-Mod-Wheel-1.7.10.jar) 
	UCHIJAAAA	MCP_Cart{1.3.0} [MC+ Cart] (MC-Mod-Cart-1.7.10.jar) 
	UCHIJAAAA	MCP_Loom{1.2.3} [MC+ Loom] (MC-Mod-Loom-1.7.10.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAA	minefantasy2{Alpha_2.7.3} [MineFantasyII] (MineFantasyII-2.7.3 (1).jar) 
	UCHIJAAAA	mobcages{1.1} [MobCages] (mobcages-1.7.10-1.2.jar) 
	UCHIJAAAA	modularpots{1.7.10.14} [Modular Flower Pots] (ModularPots-1.7.10.14.jar) 
	UCHIJAAAA	Mystcraft{0.12.3.02} [Mystcraft] (mystcraft-1.7.10-0.12.3.02.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.7.10-3.0.0b45-dev-universal (1).jar) 
	UCHIJAAAA	bq_npc_integration{2.0.18} [NPC Integration] (NPCIntegration-2.0.18.jar) 
	UCHIJAAAA	questbook{2.1.0-1.7.10} [Better Questing Quest Book] (questbook-2.1.0-1.7.10.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHIJAAAA	AS_Ruins{15.4} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (SecretRoomsMod.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	siegemode{1.0} [Siege Mode] (siegemode-1.0.jar) 
	UCHIJAAAA	SoManyEnchantments{0.2.0} [Rin's So Many Enchantments] (SoManyEnchantments V0.2.0 BETA.jar) 
	UCHIJAAAA	spacore{01.05.12} [SpACore] (SpACore-1.7.10-01.05.12.jar) 
	UCHIJAAAA	bq_standard{2.0.127} [Standard Expansion] (StandardExpansion-2.0.127.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.9.8} [Storage Drawers] (StorageDrawers-1.7.10-1.9.8.jar) 
	UCHIJAAAA	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar) 
	UCHIJAAAA	throwabletorchmod{1.3} [ThrowableTorchMod] (ThrowableTorchMod-1.7.10-1.3.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	TinyStorage{1.22.0_211} [Tiny Storage] (TinyStorage-1.22.0_211.jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UCHIJAAAA	TolkienTweaks{build-29} [Tolkien Tweaks] (TolkienTweaks-build-29.jar) 
	UCHIJAAAA	TownBuilder{1.0.0-Build8} [Town Builder] (Town-Builder-1.0.0-Build8 (1).jar) 
	UCHIJAAAA	trashslot{1.0.31} [TrashSlot] (trashslot-mc1.7.10-1.0.31.jar) 
	UCHIJAAAA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJAAAA	vending{1.2.3} [vending] (vending-v1.2.3.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHIJAAAA	waystones{1.0.4} [Waystones] (Waystones-mc1.7.10-1.0.4.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	wolfarmor{1.0.2} [Wolf Armor and Storage] (wolfarmor-1.0.3.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJAAAA	yegamolchattels{1.1.1.1} [Ye Gamol Chattels] (YeGamolChattels-1.1.1.1 (1).jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	UCHIJAAAA	NEI-Mystcraft-Plugin{02.01.09} [NEI Mystcraft Plugin] (MystNEI-Plugin-1.7.10-02.01.09.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	SpACore ASM Transformers: 
		GLStateManager: false
		GLStateManager debug output: false
		Debug screen replacer: true
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['King_Araphor'/32, l='Middle_Earth_Mordor', x=26419.50, y=110.10, z=18104.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 10
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.3.0 - Build 10.18.10.4013
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by RangerNorth** [comment]
I run 110 mods on my server but im using a single player world to test the mod first. Sorry if you didnt want the whole report!

**Comment by MggMuggins** [comment]
Well, it's definitely this mod that caused the crash. I looked into the code and it looks like it's trying to give you a kit that you don't have selected. It may just be because it's on SP, but try selecting a kit.

**Comment by RangerNorth** [comment]
Okay, but thing is I did have a kit selected because I noticed you can't join a siege match without a kit when I tried joining without one it usually would say to "Select a Kit " and it would give the command how to as well. I will try it again just for the sake of how much I love this mod so far.

**Comment by MggMuggins** [comment]
Well, either the player is null, or the kit is null. [Here](https://github.com/TheChildWalrus/SiegeMode/blob/master/SiegeMode/src/main/java/siege/common/siege/Siege.java#L777) is the line that the crash is complaining about. Unless the assignment statement in line 776 is not working, the only explanation would be that entityplayer is null, which doesn't make a whole lot of sense either. I'm going to get a gradle environment set up and throw in an assert to make sure that isn't the case. I'll get back to you soon.

**Comment by MggMuggins** [comment]
Alright, try [this](https://www.dropbox.com/s/nshpxehhv7t57ox/siegemode-test.jar?dl=0) jar. (Just install it like a usual mod).

**Comment by RangerNorth** [comment]
Didnt work still is crashing. 

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/20/17 5:49 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at siege.common.siege.Siege.applyPlayerKit(Siege.java:778)
	at siege.common.siege.Siege.onPlayerRespawn(Siege.java:750)
	at siege.common.EventHandler.onPlayerRespawn(EventHandler.java:189)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_897_EventHandler_onPlayerRespawn_PlayerRespawnEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerRespawnEvent(FMLCommonHandler.java:560)
	at net.minecraft.server.management.ServerConfigurationManager.func_72368_a(ServerConfigurationManager.java:486)
	at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:860)
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:50)
	at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by MggMuggins** [comment]
My edit did nothing. I assume I need to enable assertions, and I have no idea how to do that. I was also able to re-create your symptoms. I'll continue the bedugging process to see if I can make any headway.

**Comment by RangerNorth** [comment]
What happened was I created a kit had it equiped and was a part of the siege. I jumped off a tower leading to my death, I click respawn the game loads me in then after 3 seconds the game crashes. It doesnt load my kit into my inventory after respawn. My understanding is that with the kit being made and that I selected it in order to play it should load me in with that kit until I change it through using the /siege_kit apply (kit) command.

**Comment by RangerNorth** [comment]
I appreciate the help!

**Comment by MggMuggins** [comment]
Did you get an error message in the chat before you crashed?

**Comment by RangerNorth** [comment]
No I did not get an error message.

**Comment by MggMuggins** [comment]
Must have been something I did wrong then. We really need to wait till Mevans gets his hands on this issue.

**Comment by RangerNorth** [comment]
Okay thank you!

**Comment by TheChildWalrus** [comment]
The kit was null for some reason. If you were participating on a siege, are you sure that your team had kits assigned? A lack of available kits might have been the cause here.

**Comment by RangerNorth** [comment]
Okay that probably explains it I only had the one kit made to test it, thanks you. Btw could you make a command for sieges that bypasses the kits so if you wanted to join in a siege you could play but with your own inventory, kinda like the keep inventory command but except it's your kit kinda hard to explain without going into full story mode.

**Comment by OtisGoodman** [comment]
@RangerNorth @TheChildWalrus can you guys close this.
The problem is resolved
